import Head from "next/head";
import Image from "next/image";
import ClientOnly from "../components/ClientOnly";
import FormAdd from "../components/formAdd";
import Users from "../components/Users";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Next.js example with graphql and firebird
        </h1>
        <p className={styles.description}>
          <strong> Using Apollo Client for client-side data</strong>
          <br></br>
          <br></br>
          Client-side rendering is what we typically do in React apps. The
          browser requests the app, the page loads, then React requests the data
          and presents it to the user.
        </p>
       
          <FormAdd />
        
        <h2>Users</h2>
        <ClientOnly>
          <Users />
        </ClientOnly>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
